export * from './Eye.icon';
export * from './Minus.icon';
export * from './XMark.icon';
export * from './Check.icon';
export * from './People.icon';
export * from './Thrash.icon';
export * from './UserTag.icon';
export * from './Teacher.icon';
export * from './SwitchOn.icon';
export * from './Dashboard.icon';
export * from './ChevronUp.icon';
export* from './ChevronLeft.atom';
export * from './ChevronDown.icon';
export * from './ChevronLeft.atom';
export * from './HomePageBanner.icon';
export * from './ChevronLeftCircle.icon';
export * from './StudentsPageBanner.icon';
export * from './ManagementPageBanner.icon';