export * from './Home/Home.page';
export * from './Users/Users.page';
export * from './Login/Login.page';
export * from './Report/Reports.page';
export * from './Students/Students.page';
export * from './Management/Management.page';
export * from './Management/ViewClass/ViewClass.page';
export * from './Students/ViewStudent/ViewStudent.page';
export * from './Students/RegisterStudent/RegisterStudent.page';